### ISSUE TITLE
SINCE code example in Readme.md has mistake

### ISSUE THREAD

**Issue by AgenturSofa** [Clivern/Imap#2]
The code example suggest a usage as follows:
`$search->addCondition(new Since(date("j F Y")));`

If you do it like this, it throws a Notice: Unknown search criterion: SINCE (errflg=2) and stops working.
You should use SINCE without date() as suggested in http://php.net/manual/en/function.imap-search.php Example 1 

If the code example was `$search->addCondition(new Since("j F Y"));` instead. Everything works fine. Cheers! :)

**Comment by Clivern** [comment]
@AgenturSofa are you sure of this since on the example 
```php
$some   = imap_search($conn, 'SUBJECT "HOWTO be Awesome" SINCE "8 August 2008"', SE_UID);
```
in the readme

```
$search->addCondition(new Since(date("j F Y")))
# will be 
$search->addCondition("12 November 2018");
```
```
    public function __construct($data)
    {
        $this->data = $data;
    }
    /**
     * Query String
     *
     * @return string
     */
    public function __toString()
    {
        return "SINCE \"{$this->data}\"";
    }
```

**Comment by AgenturSofa** [comment]
Aw crap. I used the example wrong... I'm so sorry.

**Comment by Clivern** [comment]
no problem, that is fine. at least your issue solved!
