### ISSUE TITLE
hi i want to ask how to get a message using uid

### ISSUE THREAD

**Issue by nancysavchenko** [Clivern/Imap#20]

**Comment by Clivern** [comment]
well, you can by looping through messages and get the message that has `$message->header()->get('uid')` equal the given `uid`. but you can't search the mail server using a uid and it is not even unique. i remember it change when you move message from mailbox to another

**Comment by nancysavchenko** [comment]
I mean I want to get a message using uid

**Comment by nancysavchenko** [comment]
> 
> 
> well, you can by looping through messages and get the message that has `$message->header()->get('uid')` equal the given `uid`. but you can't search the mail server using a uid and it is not even unique. i remember it changes when you move message from mailbox to another

I mean I want to get a message using uid
